// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7yKudppNyCf6IJJ2iwiMT_NdagalrVtU',
    appId: '1:303314621604:web:8af255cc43653662b7c231',
    messagingSenderId: '303314621604',
    projectId: 'chat-app-78a50',
    authDomain: 'chat-app-78a50.firebaseapp.com',
    storageBucket: 'chat-app-78a50.appspot.com',
    measurementId: 'G-EFMX17N1BK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0PGXMvP1KvAvp1iCL8j_y-I1juFhXjHE',
    appId: '1:303314621604:android:81176be847bfbc8ab7c231',
    messagingSenderId: '303314621604',
    projectId: 'chat-app-78a50',
    storageBucket: 'chat-app-78a50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLL69yiQGYIH-Z4LVqG1LQQ6puxQPh0y8',
    appId: '1:303314621604:ios:cc321c0637601866b7c231',
    messagingSenderId: '303314621604',
    projectId: 'chat-app-78a50',
    storageBucket: 'chat-app-78a50.appspot.com',
    iosClientId: '303314621604-gaovjijr8d1kupo5ivni1v6o8hmvlthg.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLL69yiQGYIH-Z4LVqG1LQQ6puxQPh0y8',
    appId: '1:303314621604:ios:cc321c0637601866b7c231',
    messagingSenderId: '303314621604',
    projectId: 'chat-app-78a50',
    storageBucket: 'chat-app-78a50.appspot.com',
    iosClientId: '303314621604-gaovjijr8d1kupo5ivni1v6o8hmvlthg.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
